version: '3.1'

services:

  db:
    image: mariadb:10.3
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=example

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
